### ISSUE TITLE
need heroku support

### ISSUE THREAD

**Issue by rsoorajs** [kfur/torrentit#2]
kindly add heroku support

**Comment by kfur** [comment]
Heroku prohibit using peer-to-peer

**Comment by rsoorajs** [comment]
ok bro.i will try on ubuntu.

but i dont ubderstand these 2 env vars

BOT_AGENT_CHAT_ID &Bot id

actually what client it..give an example for those two

**Comment by kfur** [comment]
CHAT_WITH_BOT_ID - name of your bot
BOT_AGENT_CHAT_ID - id of user you want to use to download files larger than 50 MB

in `client = TelegramClient(StringSession(get_client_session()), api_id, api_hash)`
replace `StringSession(get_client_session())` to string like "bot"
and no need to set `CLIENT_SESSION`

**Comment by pseudokawaii** [comment]
> CHAT_WITH_BOT_ID - name of your bot
> BOT_AGENT_CHAT_ID - id of user you want to use to download files larger than 50 MB
> 
> in `client = TelegramClient(StringSession(get_client_session()), api_id, api_hash)`
> replace `StringSession(get_client_session())` to string like "bot"
> and no need to set `CLIENT_SESSION`

By 'bot name', do you mean username? And if i replace `StringSession(get_client_session())` with 'bot', will i be able to transfer files larger than 50 MB?

**Comment by kfur** [comment]
> By 'bot name', do you mean username? And if i replace StringSession(get_client_session()) with 'bot', will i be able to transfer files larger than 50 MB?
@pseudokawaii
it's already old code, i made small refactor for more simplicity and less env vars
